# Generated by Django 3.2.6 on 2021-09-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210909_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ManyToManyField(to='home.Cliente')),
            ],
        ),
    ]
