# Generated by Django 3.2.6 on 2021-09-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='imagen',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
