# Generated by Django 3.2.6 on 2021-09-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_estudiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
    ]
