# Generated by Django 3.2.6 on 2021-09-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_estudiante_estudiantes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
    ]
